name: deploy-shared

on:
  push:
    branches:
      - master
    paths:
      - "shared/**"

defaults:
  run:
    working-directory: shared

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
